variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

default:
  image: maven:3.8.3-ibmjava-8-alpine

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: '$CI_COMMIT_TAG'
      when: never
    - when: always

cache:
  paths:
    - .m2/repository

stages:
  - test
  - release
  - deploy

verify:jdk8:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
    - awk -F"," '{ lines += $8 + $9; covered += $9 } END { print covered, "/", lines, "lines covered"; print 100*covered/lines, "% covered" }' target/site/jacoco/jacoco.csv || echo "0.0 % covered"
  coverage: '/\d+.*\d+ \% covered/'
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

maven-release:
  stage: release
  before_script:
    - 'which ssh-agent || ( apk update && apk add openssh-client git )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add - > /dev/null
    - mkdir -m 700 -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - git config --global user.email "alex_se@hotmail.fr"
    - git config --global user.name "Gitlab Agent"
  script:
    - git checkout -B "$CI_BUILD_REF_NAME"
    - mvn release:prepare -Dmaven.test.skip=true -s ci_settings.xml -B
    - mvn release:perform -Dmaven.test.skip=true -s ci_settings.xml -B
  needs:
    - "verify:jdk8"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - when: never

deploy:jdk8:
  stage: deploy
  script:
    - 'mvn $MAVEN_CLI_OPTS deploy -Dmaven.test.skip=true -s ci_settings.xml'
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

.pages-deploy:
  stage: deploy
  image: node:10.0.0-alpine
  dependencies: []
  before_script:
    - npm install gitbook-cli -g
    - gitbook fetch 3.2.3
    - gitbook install
  script:
    - gitbook build ./wiki public

pages-test:
  extends: .pages-deploy
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  extends: .pages-deploy
  artifacts:
    paths:
      - public
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
